### ISSUE TITLE
[BUG] Crash on launch with latest version

### ISSUE THREAD

**Issue by Saereth** [auioc/arnicalib-mcmod#10]
### Description

After updating to Arnicalib 5.6.1 the game crashes immediately on launch

### Environment

running the FTB Inferno modpack
mc 1.18.2
forge 40.1.80
Arnicalib 5.6.1

### Reproduction steps

Update Arnicalib to 5.6.1 from 5.4.4 in the pack and experience the crash, 5.4.4 does not crash

### Expected behavior

To not crash

### Relevant logs

https://gist.github.com/Saereth/ffc47ae03a7c47b50b5586b3baf2f416

**Comment by WakelessSloth56** [comment]
There is a conflict between ArnicaLib and **[Brutalbosses](https://www.curseforge.com/minecraft/mc-mods/brutal-bosses-dungeon)** , because they both modify class `net/minecraft/world/entity/projectile/Projectile` using Mixin.

---

Brutalbosses merges a new `tick` method into the class that overrides the original method: ([Reference](https://github.com/someaddons/dungeonbosses/blob/bc393dc26ee37096ce3054b56e030aee90f91c22/src/main/java/com/brutalbosses/mixin/ProjectileHitActionMixin.java#L41-L49))

```java
// Decompiled from Projectile.class in .mixin.out folder
@MixinMerged(mixin = "com.brutalbosses.mixin.ProjectileHitActionMixin", priority = 1000, sessionId = "5ed0ac78-b20f-4824-9333-eae64ee17fe7")
public void m_8119_() {
    super.m_8119_(); // net.minecraft.world.entity.Entity#tick()
    if (this.maxLifeTime != 0L && this.f_19853_.m_46467_() > this.maxLifeTime) {
        this.m_142687_(Entity$RemovalReason.DISCARDED);
    }
}
```

But ArnicaLib needs to inject some code into the original method: ([Reference](https://github.com/auioc/arnicalib-mcmod/blob/1bb1a649b6d0c35088775400d7d2ffde7ee5cff0/src/main/java/org/auioc/mcmod/arnicalib/mod/mixin/common/MixinProjectile.java#L26-L39))

```java
// Decompiled from Projectile.class in forge-1.18.2-40.1.80-srg.jar
public void m_8119_() {
    if (!this.f_150164_) {
        // Some injected code
        this.m_146855_(GameEvent.f_157778_, this.m_37282_(), this.m_142538_());
        this.f_150164_ = true;
    }
    if (!this.f_37246_) {
        this.f_37246_ = this.m_37276_();
    }
    super.m_8119_();
}
```

Obviously this injection point does not exist after the class has been modified by Brutalbosses.

---

In my opinion, it should not override the original method unless there is no other way.
You can try giving feedback to the developer of Brutalbosses, I will also try to find a solution.

**Comment by Saereth** [comment]
I opened an issue with the BrutalBoss dev as well
https://github.com/someaddons/dungeonbosses/issues/47

Thank you both for looking into it

**Comment by WakelessSloth56** [comment]
You can try this dev build:

> https://github.com/auioc/arnicalib-mcmod/suites/8748688885/artifacts/396227145

If the problem is fixed, please reply.

**Comment by WakelessSloth56** [comment]
If the problem is fixed and the developer of Brutalbosses does not provide his solution in 3 days, I will merge branch `issue-10` into the main branch and release a new version.

**Comment by Saereth** [comment]
@WakelessSloth56 this did solve the issue, nice! ok we'll see what brutal bosses does I suppose
